apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-pythonwebapp
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pythonwebapp
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Object
      object:
        target:
          kind: Service
          name: pythonwebapp
        metricName: requests_per_second_pythonwebapp
        targetValue: 30
